### ISSUE TITLE
Hausdorff, number of voxels or mm?

### ISSUE THREAD

**Issue by dorianps** [codalab/EvaluateSegmentation#1]
First, let me thank you for this great tool.

I am using your tool for some automatic lesion segmentation. Question is: what does the Hausdorff variables represent, number of voxels or the metric distance in millimeters.

Dorian

**Comment by abdelaziztaha** [comment]
Hausdorff distance, and all other distances are measered in voxels. 
Regards

**Comment by hmeine** [comment]
Note that mm would often be preferable (and cannot be simply converted in case of anisotropic voxel sizes).
